id = "zed-glua"
name = "Garry's Mod Lua Support"
version = "0.0.1"
schema_version = 1
authors = ["Vaqxai <vaqxai@gmail.com>", "Pollux12"]
description = "Adds support for the Garry's Mod Lua variant to Zed, complete with LSP support (lsp by Pollux12)"
repository = "https://github.com/vaqxai/zed-glua"
